# Generated by Django 4.2.13 on 2024-07-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_contact_education_experience_portfolio_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
